name: k6 Performance Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  k6-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          sudo gpg --keyserver keyserver.ubuntu.com --recv-keys C780D0BDB1A69C86
          sudo gpg --export --armor C780D0BDB1A69C86 | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
      - name: Install dev dependencies
        run: npm ci
      - name: Ensure results directory exists
        run: mkdir -p results
      - name: Run k6 load test (Petstore)
        run: npm run petstore-load
      - name: Upload HTML and JSON reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-reports
          path: results/
